{% set name = "plotly-ecdf" %}
{% set version = "0.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/plotly-ecdf-{{ version }}.tar.gz
  sha256: 44977706b52da8d5858b91ff0e9fa501c72f5098c72e31e49a0c403e0833f790

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python {{ python_min }}
  run:
    - pandas >=1.0.0
    - plotly >=4.0.0
    - python >={{ python_min }}

test:
  imports:
    - plotly_ecdf
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/benlindsay/plotly-ecdf
  summary: Enables plotting ECDF curves using Plotly with a similar API to Plotly Express
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
